'''
Jan 20 03:25:08 fakehost logrotate: ALERT exited abnormally with [1]
Jan 20 03:25:09 fakehost run-parts(/etc/cron.daily)[20447]: finished logrotate
Jan 20 03:26:21 fakehost anacron[28969]: Job 'cron.daily' terminated
Jan 20 03:26:22 fakehost anacron[28969]: Normal exit (1 job run)
Jan 20 03:30:01 fakehost CROND[31462]: (root) CMD (/usr/lib64/sa/sa1 1 1)
Jan 20 03:30:01 fakehost CROND[31461]: (root) CMD (/var/system/bin/sys-cmd -F > /dev/null 2>&1)
Jan 20 05:03:03 fakehost ntpd[3705]: synchronized to time.faux.biz, stratum 2
Jan 20 05:03:03 fakehost ntpd[3705]: synchronized to time.faux.biz, stratum 2
Jan 20 05:03:03 fakehost ntpd[3705]: synchronized to time.faux.biz, stratum 2
Jan 20 05:03:03 fakehost ntpd[3705]: synchronized to time.faux.biz, stratum 2
Jan 20 05:20:01 fakehost rsyslogd: [origin software="rsyslogd" swVersion="5.8.10" x-pid="20438" x-info="http://www.rsyslog.com"] start
Jan 20 05:22:04 fakehost cs3[31163]:  Q: ".../bin/rsync -LD ": symlink has no referent: "/var/syscmds/fakehost/runit_scripts/etc/runit/service/superImportantService/run"#012Q: ".../bin/rsync -LD ": rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1039) [sender=3.0.6]
Jan 20 05:22:04 fakehost cs3[31163]:  I: Last 2 quoted lines were generated by "/usr/local/bin/rsync -LD --recursive --delete --password-file=/var/syscmds/modules/rsync_password /var/syscmds/fakehost syscmds@fakehost::syscmds_rsync"
Jan 20 05:22:08 fakehost cs3[31163]:  Q: ".../sbin/sv restart": ok: run: /export/service/cool-service: (pid 32323) 0s
Jan 20 05:22:08 fakehost cs3[31163]:  I: Last 1 quoted lines were generated by "/sbin/sv restart /export/service/cool-service"
Jan 20 05:22:09 fakehost cs3[31163]:  R: cs3:  The cool service on fakehost does not appear to be communicating with the cool service leader.  Automating a restart of the cool service in attempt to resolve the communication problem.
Jan 20 05:22:37 fakehost ACCT_ADD: WARNING: Manifest /var/syscmds/inputs/config-general/doit.txt has been processed already, bailing

OUTPUT:
logrotate run-parts(/etc/cron.daily)[20447] anacron[28969] CROND[31462] CROND[31461] ntpd[3705] rsyslogd cs3[31163] ACCT_ADD TOTAL
Jan20 03:26 : 0 0 2 0 0 0 0 0 0 0 2 
Jan20 03:25 : 1 1 0 0 0 0 0 0 0 0 2 
Jan20 03:30 : 0 0 0 1 1 0 0 0 0 0 2 
Jan20 05:03 : 0 0 0 0 0 4 0 0 0 0 4 
Jan20 05:20 : 0 0 0 0 0 0 1 0 0 0 1 
Jan20 05:22 : 0 0 0 0 0 0 0 5 1 0 6 
'''
############
lines = open('log.txt').readlines()
d={}
svs = []
for line in lines:
    temp = line.split()
    date = temp[0]+temp[1]
    time = temp[2].split(':')
    hr = time[0]+':'+time[1]
    param = date + " " + hr
    if param in d.keys():
        if any(temp[4].strip(':') in x[0] for x in d[param]):
            temp1 = [i for i in d[param] if temp[4].strip(':') in i]
            a=temp1[0][1]
            a+=1
            app = [i for i in d[param] if temp[4].strip(':') not in i]+[(temp[4].strip(':'),a)]
            d[param]=app
        else:
            svs.append(temp[4].strip(':'))
            l = d[param]
            l.append((temp[4].strip(':'),1))
            d[param] = l
    else:
        svs.append(temp[4].strip(':'))
        d[param]=[(temp[4].strip(':'),1)]


############To display####################       
svs.append("TOTAL")
print " ".join(svs)
for i in d.keys():
    print i,":",
    count = 0
    temp = d[i]
    for k in svs:
        t = [i for i in temp if k in i[0]]
        if t:
            print t[0][1],
            count = count + int(t[0][1])
        else:
            print '0',
    print count,
    print ''
